on: 
# Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
  push:
    branches: [ "master" ]
    paths: ./streaming-analytics/blocks
  pull_request:
    branches: [ "master" ]
    paths: ./streaming-analytics/blocks
 

env:
  SETUP_APAMA_VERSION: 10.5.3.2
  BLOCK_BUILDER_VERSION : 10.13.0.1

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest


    steps:
      - uses: actions/checkout@v2

      - name: Cached Apama installation
      # always-upload is a fork of actions/cache allows cache to be saved even if some later steps (e.g. testing) fail
        uses: pat-s/always-upload-cache@v2.1.3

        id: cache-apama-installer
        with:
            path: ~/cached-apama-installation.tar
            key: apama-${{ runner.os }}-${{ env.SETUP_APAMA_VERSION }}

      - uses: ./.github/apama
        with:
          apama-version: ${{ env.SETUP_APAMA_VERSION }}

      - name: Test starting the Apama correlator
        # Basic test that should work on all Apama versions
        shell: bash
        run: |
          env | sort
          correlator --version
          
      - name: Test the rest of the Apama environment
        shell: bash
        # Some tools aren't in the oldest version
        if: matrix.apama-version != '9.10.0.3'
        run: |
          engine_deploy -h
          
          $APAMA_PYSYS makeproject --help
          
          which javac
          javac -version
          
          which python
          python --version
          
          which ant
          ant -version
      - name: Deploy analytics builder blocks to cumulocity
        shell: bash
        run: |
          echo Get version $BLOCK_BUILDER_VERSION of the block builder SDK
          mkdir ./block-sdk
          cd ./block-sdk
          REPO_URL=https://github.com/SoftwareAG/apama-analytics-builder-block-sdk/archive/refs/tags/$BLOCK_BUILDER_VERSION.zip
          echo Downloading from $REPO_URL
          curl --retry 2 --head $REPO_URL
          curl --retry 2 -L --output block-builder.zip $REPO_URL
          unzip -q block-builder.zip
          cd apama-analytics-builder-block-sdk-$BLOCK_BUILDER_VERSION
          echo Upload analytics builder blocks to cumulocity
          ls $GITHUB_WORKSPACE/streaming-analytics/blocks
          python3 analytics_builder build extension --input $GITHUB_WORKSPACE/streaming-analytics/blocks --cumulocity_url ${{ secrets.PARAM1 }} --username ${{ secrets.PARAM2 }}/${{ secrets.PARAM3 }} --password ${{ secrets.PARAM4 }} --name semis --restart
          
  
